#!/bin/bash

echo "🔍 Диагностика VPS logistics.xrom.org"
echo "==========================================="

echo "📡 Проверка сетевого подключения..."
curl -I http://logistics.xrom.org 2>&1 | head -5

echo ""
echo "📊 Рекомендуемые команды для выполнения на VPS:"
echo ""
echo "1. Проверка статуса сервисов:"
echo "   sudo systemctl status hromkz"
echo "   sudo systemctl status nginx"
echo "   sudo systemctl status postgresql"
echo ""
echo "2. Если сервис hromkz не запущен:"
echo "   sudo systemctl start hromkz"
echo "   sudo systemctl enable hromkz"
echo ""
echo "3. Проверка логов приложения:"
echo "   sudo journalctl -u hromkz -f --no-pager"
echo ""
echo "4. Проверка nginx логов:"
echo "   sudo tail -f /var/log/nginx/error.log"
echo ""
echo "5. Тест базы данных:"
echo "   sudo -u postgres psql -d hromkz_logistics -c '\\dt'"
echo ""
echo "6. Перезапуск всех сервисов:"
echo "   sudo systemctl restart hromkz && sudo systemctl restart nginx"
echo ""
echo "💡 Наиболее вероятная причина: Flask приложение (hromkz service) не запущено"
echo "   Выполните: sudo systemctl start hromkz"