#!/bin/bash

echo "🔧 Исправление прав доступа для logistics.xrom.org"
echo "================================================="

echo "Выполните эти команды на VPS как root:"
echo ""
echo "# 1. Остановка сервиса"
echo "sudo systemctl stop hromkz"
echo ""
echo "# 2. Исправление прав доступа"
echo "sudo chown -R hromkz:www-data /var/www/logistics.xrom.org"
echo "sudo chmod -R 755 /var/www/logistics.xrom.org"
echo "sudo chmod 775 /var/www/logistics.xrom.org"
echo ""
echo "# 3. Создание директории для сокета с правильными правами"
echo "sudo mkdir -p /var/www/logistics.xrom.org/run"
echo "sudo chown hromkz:www-data /var/www/logistics.xrom.org/run"
echo "sudo chmod 775 /var/www/logistics.xrom.org/run"
echo ""
echo "# 4. Обновление systemd сервиса с правильным путем к сокету"
echo "sudo tee /etc/systemd/system/hromkz.service << 'EOF'"
echo "[Unit]"
echo "Description=Hrom KZ Full Logistics System"
echo "After=network.target"
echo ""
echo "[Service]"
echo "User=hromkz"
echo "Group=www-data"
echo "WorkingDirectory=/var/www/logistics.xrom.org"
echo "Environment=\"PATH=/var/www/logistics.xrom.org/venv/bin\""
echo "EnvironmentFile=/var/www/logistics.xrom.org/.env"
echo "ExecStart=/var/www/logistics.xrom.org/venv/bin/gunicorn --workers 3 --bind unix:/var/www/logistics.xrom.org/run/hromkz.sock --umask 0007 main:app"
echo "ExecReload=/bin/kill -s HUP \$MAINPID"
echo "Restart=always"
echo "RestartSec=10"
echo ""
echo "[Install]"
echo "WantedBy=multi-user.target"
echo "EOF"
echo ""
echo "# 5. Обновление Nginx конфигурации"
echo "sudo tee /etc/nginx/sites-available/logistics.xrom.org << 'EOF'"
echo "server {"
echo "    listen 80;"
echo "    server_name logistics.xrom.org;"
echo ""
echo "    location = /favicon.ico { "
echo "        access_log off; "
echo "        log_not_found off; "
echo "    }"
echo "    "
echo "    location /static/ {"
echo "        alias /var/www/logistics.xrom.org/static/;"
echo "        expires 1y;"
echo "        add_header Cache-Control \"public, immutable\";"
echo "    }"
echo ""
echo "    location / {"
echo "        include proxy_params;"
echo "        proxy_pass http://unix:/var/www/logistics.xrom.org/run/hromkz.sock;"
echo "        proxy_set_header Host \$host;"
echo "        proxy_set_header X-Real-IP \$remote_addr;"
echo "        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;"
echo "        proxy_set_header X-Forwarded-Proto \$scheme;"
echo "    }"
echo "}"
echo "EOF"
echo ""
echo "# 6. Перезагрузка конфигураций и запуск"
echo "sudo systemctl daemon-reload"
echo "sudo systemctl enable hromkz"
echo "sudo systemctl start hromkz"
echo "sudo nginx -t && sudo systemctl reload nginx"
echo ""
echo "# 7. Проверка статуса"
echo "sudo systemctl status hromkz"
echo ""
echo "После выполнения этих команд сайт должен заработать!"